import { Calendar, User, ArrowLeft } from "lucide-react"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export default function BugattiChironPage() {
  return (
    <div className="min-h-screen bg-white">
      {/* Header */}
      <header className="bg-white border-b border-gray-200 px-4 py-3">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <Link href="/" className="flex items-center space-x-2">
            <div className="w-8 h-8 bg-red-500 rounded flex items-center justify-center">
              <span className="text-white font-bold text-sm">🚗</span>
            </div>
            <div className="flex flex-col">
              <span className="font-bold text-xl text-gray-900">AutoBlog</span>
              <span className="text-sm text-gray-500">Motor Vehicle Insights</span>
            </div>
          </Link>
        </div>
      </header>

      <article className="max-w-4xl mx-auto px-4 py-12">
        <Link href="/" className="inline-flex items-center text-red-500 hover:text-red-600 mb-8">
          <ArrowLeft className="w-4 h-4 mr-2" />
          Back to Home
        </Link>

        <div className="mb-8">
          <span className="bg-blue-600 text-white px-3 py-1 rounded-full text-sm font-medium mb-4 inline-block">
            HYPERCAR
          </span>
          <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-6 leading-tight">
            Bugatti Chiron: The Ultimate Expression of Speed
          </h1>
          <div className="flex items-center space-x-6 text-gray-600">
            <span className="flex items-center">
              <User className="w-4 h-4 mr-2" />
              Marcus Weber
            </span>
            <span className="flex items-center">
              <Calendar className="w-4 h-4 mr-2" />
              December 7, 2024
            </span>
          </div>
        </div>

        <img
          src="/bugatti-chiron-blue-carbon-fiber-hypercar-detailed.jpg"
          alt="Bugatti Chiron"
          className="w-full h-96 object-cover rounded-lg mb-8"
        />

        <div className="prose prose-lg max-w-none">
          <p className="text-xl text-gray-700 mb-6 leading-relaxed">
            The Bugatti Chiron stands as the ultimate expression of automotive excess, pushing the boundaries of what's
            possible in terms of power, luxury, and engineering excellence.
          </p>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Unprecedented Power</h2>
          <p className="text-gray-700 mb-6 leading-relaxed">
            The quad-turbocharged 8.0-liter W16 engine produces an astounding 1,479 horsepower and 1,180 lb-ft of
            torque. This massive powerplant requires four turbochargers and an intricate cooling system to manage the
            immense heat generated by such extreme performance.
          </p>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Engineering Marvel</h2>
          <p className="text-gray-700 mb-6 leading-relaxed">
            Every component of the Chiron has been engineered to handle extreme forces. The carbon fiber monocoque,
            titanium roll cage, and specially developed Michelin tires work together to safely contain and channel the
            W16's massive output. The seven-speed dual-clutch transmission can handle the engine's torque while
            providing lightning-fast shifts.
          </p>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Luxury Redefined</h2>
          <p className="text-gray-700 mb-6 leading-relaxed">
            Despite its extreme performance capabilities, the Chiron remains a luxurious grand tourer. The interior
            features the finest materials, from hand-stitched leather to machined aluminum controls. Every surface is
            crafted to perfection, creating an environment worthy of the Bugatti name.
          </p>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">The Pinnacle</h2>
          <p className="text-gray-700 mb-6 leading-relaxed">
            With a top speed of 261 mph (electronically limited) and acceleration from 0-60 mph in just 2.4 seconds, the
            Chiron represents the absolute pinnacle of automotive achievement. It's not just a car – it's a statement
            about what's possible when engineering excellence meets unlimited resources.
          </p>
        </div>

        <div className="mt-12 pt-8 border-t border-gray-200">
          <Link href="/">
            <Button className="bg-red-500 hover:bg-red-600 text-white">← Back to All Articles</Button>
          </Link>
        </div>
      </article>
    </div>
  )
}
